spring.application.name=careflow

# Server Configuration
server.port=8081

# OpenRouter API
openrouter.api.key=${OPENROUTER_API_KEY:YOUR_OPENROUTER_API_KEY}

# AWS RDS MySQL Database
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://database-1.cfmas0qmqjpb.ap-south-1.rds.amazonaws.com/careflow
spring.datasource.username=Mohan
spring.datasource.password=Mohan.143

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false